name: Build Project

on:
	push:
		branches:
			- master

jobs:
	build:
		runs-on: ubuntu-latest

		steps:
		- name: Checkout Repo
			uses: actions/checkout@v2

		- name: Setup Node
			uses: actions/setup-node@v2
			with:
				node-version: '18'
		
		- name: Install Deps
			run: npm install

		- name: Build React Project
			run: npm run build

		- name: Archive Build Artifacts
			uses: actions/upload-artifact@v2
			with:
				name: build-artifacts
				path: build
